kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
  labels:
    envt: dev
    tier: backend
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchExpressions:
      - key: envt
        operator: In
        values:
          - dev
          - prod
      - key: tier
        operator: Exists
  template:
    metadata:
      labels:
        envt: dev
        tier: backend
    spec:
      containers:
      - name: thirdcontainer
        image: ecr_repo/ecr_image:lates1
        ports:
          - containerPort: 80
